volumes:
  gopher-redis-data:
    name: gopher-redis-data
  gopher-postgres-data:
    name: gopher-postgres-data

services:
  gopher-server:
    build:
      context: .
      dockerfile: ./compose/.server.dockerfile
    image: gopher-server:latest
    container_name: gopher-server
    env_file:
      - ./.envs/.server.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app:z
    networks:
      - gopher-network
    healthcheck:
      test: [ "CMD", "/app/healthCheck.sh" ]
      interval: 1m30s
      retries: 5
      start_period: 30s
      timeout: 30s
    depends_on:
      gopher-redis:
        condition: service_healthy
      gopher-postgres:
        condition: service_healthy

  gopher-redis:
    image: redis:latest
    container_name: gopher-redis
    volumes:
      - gopher-redis-data:/data
    networks:
      - gopher-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      retries: 5
      timeout: 30s
      start_period: 30s

  gopher-postgres:
    image: postgres:16-alpine
    container_name: gopher-postgres
    volumes:
      - gopher-postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres.env
    ports:
      - "5432:5432"
    networks:
      - gopher-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 1m30s
      retries: 5
      timeout: 30s
      start_period: 30s

networks:
  gopher-network:
    driver: bridge
